---
- hosts: My_Group
  become_user: ansadmin
  become: true
  tasks:
    - name: copy tomcat tar.gz file from remote
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.91/bin/apache-tomcat-8.5.91.tar.gz
        dest: /opt
    - name: uarchive the tar file
      unarchive:
        src: /opt/apache-tomcat-8.5.91.tar.gz
        dest: /opt
        remote_src: yes
    - name: Task -2 Install Java using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - openjdk-11-jdk
    - name: start tomcat service
      command: nohup /opt/apache-tomcat-8.5.91/bin/startup.sh
    - name: copy artifact from ansible master to tomcat server
      copy:
        src: /etc/ansible/playbooks/webapp/target/webapp.war
        dest: /opt/apache-tomcat-8.5.91/webapps
        remote_src: yes
